name: hello_world
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [main]
env:
  AWS_DEFAULT_REGION: us-east-2
  STAGE: stage
jobs:
  build_and_deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{env.AWS_DEFAULT_REGION}}
#PRIVATE REPOSITORY LOGIN
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Check Node.js version
      run: node -v

    - name: Check npm version
      run: npm -v

    - name: Install dependencies (npm)
      run: npm install

    - name: Install Serverless
      run: npm install -g serverless

    - name: Check Serverless version
      run: sls -v

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy Serverless application
      run: sls deploy --stage ${{env.STAGE}}